server:
  port: 14001

spring:
  application:
    name: email-service
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://119.29.23.121:3306/library2?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: ba36754794
  redis:
    host: 119.29.172.177
    port: 6379
  rabbitmq:
    host: 119.29.172.177
    port: 5672
    virtualHost: host1
    username: admin
    password: admin
  mail:
    #smtp服务主机  qq邮箱则为smtp.qq.com
    host: smtp.163.com
    #服务协议
    protocol: smtp
    # 编码集
    default-encoding: UTF-8
    #发送邮件的账户
    username: mpy_library@163.com
    #授权码
    password: LDBAUPLNMFLUSVEZ
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

eureka:
  client:
    service-url:
      defaultZone: http://10.10.102.163:7001/eureka/
  instance:
    prefer-ip-address: true